### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by zubairahmed-ai** [akshaybahadur21/HandMovementTracking#2]
When I run this I get this error

```
Traceback (most recent call last):
  File "Write.py", line 37, in <module>
    for i in xrange (1,len(pts)):
NameError: name 'xrange' is not defined
```

**Comment by pulkitdhingraa** [comment]
> When I run this I get this error
> 
> ```
> Traceback (most recent call last):
>   File "Write.py", line 37, in <module>
>     for i in xrange (1,len(pts)):
> NameError: name 'xrange' is not defined
> ```

This is because the code was originally written in Python 2. You are probably using Python3, therefore the name 'xrange' is changed to 'range'

**Comment by akshaybahadur21** [comment]
@pulkitd2699 - Thank you.
I believe that is the case.
Closing the issue now @zubairahmed-ai .
