### ISSUE TITLE
How to begin?

### ISSUE THREAD

**Issue by duttanaman1** [akshaybahadur21/HandMovementTracking#4]
how does the camera detect the finger point or pen point in your case?
The files open, but how to begin?

**Comment by blwinner** [comment]
use 
Lower_green = np.array([110,50,50])
Upper_green = np.array([130,255,255])
and cv2.inRange
to filter hsv pixeles
and track it, so dont need begin, just do it

**Comment by akshaybahadur21** [comment]
Resolved.
